### ISSUE TITLE
Error to Send Message

### ISSUE THREAD

**Issue by ianfleon** [capcom6/android-sms-gateway-ts#44]
Please help. I was try send message but FAILED. In messages tab show RESULT_NO_DEFAULT_SMS_APP

**Comment by ianfleon** [comment]
Done. you have to set Default SIM for send sms in SIM CARD SETTING

**Comment by capcom6** [comment]
Hello!

Thank you for reporting this issue.
I'll add an entry to the FAQ regarding this error for future reference.

May I close this issue?

**Comment by ianfleon** [comment]
> Hello!
> 
> Thank you for reporting this issue. I'll add an entry to the FAQ regarding this error for future reference.
> 
> May I close this issue?

Yes Sir!
